### ISSUE TITLE
Error on PacketInEvent.

### ISSUE THREAD

**Issue by hseermc** [LeavesMC/Leaves#378] opened 2024-11-27 02:10 UTC
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21.1-81-master@ec5a806 (2024-11-16T03:56:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### 预期的行为 Expected behavior

jade协议可以正常使用

### 观测到的实际行为 Observed/Actual behavior

出现报错

### 复现步骤 Steps/models to reproduce

我不确定服务器内玩家做了什么……但是有时会出现报错

### 插件与数据包列表。 Plugin and Datapack List.

已启用3个数据包：[vanilla（内置）], [file/bukkit（世界）], [paper（内置）]

[10:08:34 INFO]: Server Plugins (98):
[10:08:34 INFO]: Paper Plugins:
[10:08:34 INFO]:  - HuskHomes
[10:08:34 INFO]: Bukkit Plugins:
[10:08:34 INFO]:  - AuthMe, BedrockPlayerSupport, BetterRTP, Bump, *ChineseName, Citizens, CMILib, CoreProtect, CrossplatForms, Cultivation
[10:08:34 INFO]:  CustomJoinAndLeaveMessages, DecentHolograms, DeluxeMenus, DynaTech, EClean, EcoPower, ElectricSpawners, ElementManipulation, Essentials, EssentialsSpawn
[10:08:34 INFO]:  EssentialsWarpGUI, ExoticGarden, ExtraGear, ExtraTools, FastMachines, FinalTECH-Changed, floodgate, Floodgate-Skript, FluffyMachines, FNAmplifications
[10:08:34 INFO]:  FoxyMachines, Gastronomicon, GeneticChickengineering, Geyser-Spigot, GlobalWarming, GroupManager, GSit, GuizhanCraft, GuizhanLibPlugin, HSEERTECH
[10:08:34 INFO]:  Images, InfiniteScoreboard, InfinityExpansion, InteractionVisualizer, InventoryRollbackPlus, ItemSwapperPlugin, LegendaryGuild, LiteAnnouncer, LiteSignIn, LiteXpansion
[10:08:34 INFO]:  mcMMO, MiniMOTD, MobCapturer, MomoTech, Multiverse-Core, Multiverse-NetherPortals, Networks, nightcore, PlaceholderAPI, PlayerTitle
[10:08:34 INFO]:  PlugManX, PrivateStorage, ProtocolLib, Quaptics, QuickShop-Hikari, RedstoneConnector, Residence, RykenSlimefunCustomizer, SFCalc, ShopGUIPlus
[10:08:34 INFO]:  ShopGUIPlus-SellGUI, SimpleMaterialGenerators, SimpleUtils, SkinsRestorer, Skript, skript-reflect, Slimefun, SlimefunWarfare, SlimeGlue, SlimeHUD
[10:08:34 INFO]:  SlimeTinker, SoulJars, Supreme, TAB, TimedRewards, TpaForm, TranscEndence, TrChat, UltimateAntiBot, UltimateAutoRestart
[10:08:34 INFO]:  UltimateGenerators, Uniporter, Vault, ViaBackwards, ViaVersion, XConomy, ZMusic

### 更多详细信息。 The more information.

报错如下https://mclo.gs/Vz8FmH0
（已经问过trchat，报错里面的trchat只负责发包监听功能）

**Comment by s-yh-china** [comment] 2024-11-27 02:27
应该是jade版本不匹配导致的，你可以让玩家升级最新的jade版本，或者干脆把这个功能关掉
此问题会在最新的jade中得到优化，因为添加了关于协议版本的事宜

**Comment by s-yh-china** [comment] 2024-12-28 07:34
Duplicate of #384

**Closed by s-yh-china** 2024-12-28 07:34 UTC
Labels: bug, needs testing
