### ISSUE TITLE
对于issue#309的问题重现

### ISSUE THREAD

**Issue by Rebines** [LeavesMC/Leaves#319] opened 2024-08-20 08:53 UTC
### 服务端版本 LeavesMC Version

1.21-45-master@1782bd4

### 预期的行为 Expected behavior

见[#309](https://github.com/LeavesMC/Leaves/issues/309)

### 观测到的实际行为 Observed/Actual behavior

见[#309](https://github.com/LeavesMC/Leaves/issues/309)

### 复现步骤 Steps/models to reproduce

见[#309](https://github.com/LeavesMC/Leaves/issues/309)

### 插件与数据包列表。 Plugin and Datapack List.

见[#309](https://github.com/LeavesMC/Leaves/issues/309)

### 更多详细信息。 The more information.

见[#309](https://github.com/LeavesMC/Leaves/issues/309)
以下为补充内容：
> paper playermobcaps BOT_ttds
[16:44:04 INFO]: Mobcaps for player: BOT_ttds
[16:44:04 INFO]:   monster: 0/70
  creature: 10/10
  ambient: 0/0
  axolotls: 0/10
  underground_water_creature: 0/5
  water_creature: 4/5
  water_ambient: 0/20
  misc: n/a
投影文件：[https://wwcz.lanzout.com/iGcVz27ybtaj
密码:bbfc](https://wwcz.lanzout.com/iGcVz27ybtaj)
（含挂机位置）

**Comment by LittleChest** [comment] 2024-08-20 08:55
Duplicate of #309

**Comment by LittleChest** [comment] 2024-08-20 08:55
请补充至原issue 谢谢

**Closed by LittleChest** 2024-08-20 08:55 UTC
Labels: bug, needs testing
